# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Fertico App',
    'version': '11.0.0.0.2',
    "author": "Vauxoo",
    "license": "LGPL-3",
    'category': 'Hidden',
    'summary': 'Fertico App for customizations',
    'depends': [
	'project',
	'point_of_sale',
	'stock_account',
	'stock_landed_costs',
	'sale_stock',
	'mrp_workorder',
	'mrp_account',
	'purchase_mrp',
	'sale_mrp',
	'mail_push',
	'account_invoicing',
	'account_accountant',
	'purchase_requisition',
	'hr_contract',
	'board',
	'contacts',
	'web_studio',
	'account_cash_basis_base_account',
	'pos_sale',
	'base_address_city',
	'base_address_extended',
	'account_asset',
	'account_bank_statement_import',
	'account_bank_statement_import_csv',
	'account_bank_statement_import_ofx',
	'account_budget',
	'account_cancel',
	'account_check_printing',
	'account_extension',
	'account_online_sync',
	'account_reports',
	'account_yodlee',
	'analytic',
	'auth_crypt',
	'auth_signup',
	'barcodes_mobile',
	'base_automation',
	'base_automation_hr_contract',
	'base_import_module',
	'base_setup',
	'base_vat_autocomplete',
	'bus',
	'currency_rate_live',
	'decimal_precision',
	'document',
	'fetchmail',
	'google_account',
	'hr_expense_check',
	'iap',
	'l10n_generic_coa',
	'l10n_mx_edi_customer_bills',
	'l10n_mx_edi_customs',
	'l10n_mx_edi_landing',
	'l10n_mx_edi_payment',
	'l10n_mx_reports',
	'l10n_us_check_printing',
	'l10n_us_reports',
	'payment_transfer',
	'procurement_jit',
	'product_email_template',
	'product_margin',
	'resource',
	'sale_expense',
	'sale_order_dates',
	'sales_team',
	'sms',
	'web_clearbit',
	'web_diagram',
	'web_editor',
	'web_enterprise',
	'web_gantt',
	'web_grid',
	'web_kanban_gauge',
	'web_mobile',
	'web_planner',
	'web_settings_dashboard',
	'web_tour',
	'portal',
	'http_routing',
	'l10n_mx_edi_partner_defaults',
	'stock_no_negative',

	 ],
    'data': [
	],
    'demo': [
    ],
    'installable': True,
    'auto_install': True,
}
